{{- $clustername := .Values.cluster.name }}
apiVersion: rke-machine-config.cattle.io/v1
kind: Amazonec2Config
metadata:
  name: {{ $clustername }}-controlplane
  namespace: fleet-default
instanceType: t3a.medium
region: us-gov-east-1
subnetId: subnet-071b374d
vpcId: vpc-5415f83d
zone: a
sshUser: ubuntu
